name: base
channels:
  - ioam/label/dev
  - bokeh
  - etetoolkit
  - defaults
  - conda-forge
dependencies:
  - matplotlib=2.2.2
  - mpmath=0.19
  - numpy=1.14.2
  - numpydoc=0.6.0
  - six=1.11.0
  - bokeh=0.12.15=
  - scikit-learn=0.19.1
  - scipy=1.0.1
  - seaborn=0.8.1

  - pip:
    - attrs==18.1.0
    - backports.shutil-get-terminal-size==1.0.0
    - basemap==1.1.0
    - ez-setup==0.9
    - homebrew==0.0.20
    - more-itertools==4.1.0
    - nameparser==0.5.6
    - pluggy==0.6.0
    - pyerf==1.0.1
    - rope-py3k==0.9.4.post1
    - scikits.bootstrap==1.0.0
    - tables==3.4.2

