name: base
channels:
  - ioam/label/dev
  - bokeh
  - etetoolkit
  - defaults
  - conda-forge
dependencies:
  - matplotlib=2.2.2=py36ha7267d0_0
  - mpmath=0.19=py36_1
  - numpy=1.14.2=py36ha9ae307_1
  - numpydoc=0.6.0=py36_0
  - six=1.11.0=py36h0e22d5e_1
  - bokeh=0.12.15=py36_0
  - scikit-learn=0.19.1=py36hffbff8c_0
  - scipy=1.0.1=py36hcaad992_0
  - seaborn=0.8.1=py36h595ecd9_0

  - pip:
    - attrs==18.1.0
    - backports.shutil-get-terminal-size==1.0.0
    - basemap==1.1.0
    - ez-setup==0.9
    - homebrew==0.0.20
    - more-itertools==4.1.0
    - nameparser==0.5.6
    - pluggy==0.6.0
    - pyerf==1.0.1
    - rope-py3k==0.9.4.post1
    - scikits.bootstrap==1.0.0
    - tables==3.4.2

